# Generated by Django 3.0 on 2020-01-22 11:55

import UserManagement.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usr_role',
            fields=[
                ('roleID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=20)),
                ('roleDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='usr_user',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('loginID', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=6)),
                ('birthdate', models.DateField()),
                ('phone', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=70)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(default='default value', max_length=50)),
                ('modified_on', models.DateField(default=datetime.datetime(2020, 1, 22, 11, 55, 2, 44980, tzinfo=utc))),
                ('modified_by', models.CharField(default='default value', max_length=50)),
                ('is_active', models.CharField(default='01', max_length=2)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', UserManagement.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='usr_userRole',
            fields=[
                ('userRoleID', models.AutoField(primary_key=True, serialize=False)),
                ('roleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.usr_role')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
