# Generated by Django 3.0 on 2020-01-23 06:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_auto_20200123_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_role',
            name='roleID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usr_user',
            name='modified_on',
            field=models.DateField(default=datetime.datetime(2020, 1, 23, 6, 34, 32, 719158, tzinfo=utc)),
        ),
    ]
