# Generated by Django 3.0 on 2020-01-23 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0004_auto_20200123_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_user',
            name='modified_on',
            field=models.DateField(default=datetime.datetime(2020, 1, 23, 18, 20, 34, 716037, tzinfo=utc)),
        ),
    ]
