# Generated by Django 3.0 on 2020-01-25 05:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0005_auto_20200123_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_user',
            name='modified_on',
            field=models.DateField(default=datetime.datetime(2020, 1, 25, 5, 27, 12, 509009, tzinfo=utc)),
        ),
    ]
