# Generated by Django 3.0 on 2020-01-25 06:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0006_auto_20200125_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_user',
            name='modified_on',
            field=models.DateField(default=datetime.datetime(2020, 1, 25, 6, 33, 42, 985687, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usr_user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
