# Generated by Django 3.0 on 2020-01-25 06:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0007_auto_20200125_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_user',
            name='modified_on',
            field=models.DateField(default=datetime.datetime(2020, 1, 25, 6, 44, 24, 813060, tzinfo=utc)),
        ),
    ]
