# Generated by Django 3.0 on 2020-01-27 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0019_auto_20200127_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_user',
            name='modified_on',
            field=models.DateField(default=datetime.datetime(2020, 1, 27, 13, 0, 28, 308765, tzinfo=utc)),
        ),
    ]
