# Generated by Django 3.0 on 2020-01-27 17:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0023_auto_20200127_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_user',
            name='modified_on',
            field=models.DateField(default=datetime.datetime(2020, 1, 27, 17, 49, 37, 585416, tzinfo=utc)),
        ),
    ]
