# Generated by Django 3.0 on 2020-01-28 06:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0024_auto_20200127_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_user',
            name='modified_on',
            field=models.DateField(default=datetime.datetime(2020, 1, 28, 6, 25, 41, 636543, tzinfo=utc)),
        ),
    ]
